name: fifthbeat_project
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  models :
    path: packages/models
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.9
  convert: ^3.0.1
  assets: 
    - assets/images/


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
